### PR TITLE
Places list

### LINKED ISSUE #7: Create places view
Add an activity or fragment to show the places list: [wireframe](https://marvelapp.com/4c295bb/screen/37236999).

Show full list of places in cards (do not implement filtering yet). Add toolbar with buttons (unimplemented).

Add popover to place cards with user flags (liked, been, etc.), not implemented.

### LINKED ISSUE #8: Create places filter view
Create but do not implement place list filter view: [wireframe](https://marvelapp.com/4c295bb/screen/37237004).

Open/close on filter click and implement place view filter button count of filters applied using dummy data.

### PR DESCRIPTION
**Pull request by flibbertigibbet**
## Overview

Add places list view activity that displays a card for each destination. Add filtering bottom sheet modal that  updates filter count badge (does not implement filtering yet). Display popover on place card with user option flags (user options not yet implemented). Adds Material Design icons used by place list and home views.

## Demo

Place list:
screenshot_1519770860

Place card popover:
screenshot_1519770868

Cycling and Watershed Alliance icons over place image:
screenshot_1519771168

Filter bottom sheet:
screenshot_1519861148

Applied filter count badge:
screenshot_1519861157

## Notes

The [Material Design style toggle buttons](https://material.io/guidelines/components/buttons.html#buttons-toggle-buttons) for the filter sheet have no equivalent in Android; there is a [ToggleButton](https://developer.android.com/guide/topics/ui/controls/togglebutton.html) class available, but rather than toggle button background/foreground state, it toggles a switch or sets a highlight bar at the button base. See more disucssion [here](https://stackoverflow.com/questions/35973610/android-toggle-button-material-design). The base class for toggle-able things in Android is the [CompoundButton](https://developer.android.com/reference/android/widget/CompoundButton.html), which is used here to create a custom button style with on/off states.

Added a [library for badges](https://github.com/nekocode/Badge) that seems to work pretty well. Using the text badge option rather than the number badge for the square border.

Android `PopupMenu` lists hide their icons, but they are shown in the wireframes. To get around that, it's necessary to call `setForceShowIcon`, which is buried in the internal API of `MenuPopupHelper`.

Every place card currently shows the 'been' badge on the lower right, which serves as the button and anchor point for the popup menu of options. From the wireframes though, it appears that some variable set of applied badges for the place should appear on the bottom right. @lederer is that correct?

Also for clarification, should the 'liked' and 'want to go' buttons in the top bar serve as toggle-able filter shortcuts that behave just like the filter sheet options?

## Testing

 - Click any of the grid options from the home view to get to the places list
 - Places should load and scroll smoothly in the list
 - Popup menu should appear on 'been' badge click
 - Filter bottom sheet should open on 'filter' top bar button click
 - Filter sheet buttons to clear and close should work as expected
 - Filter buttons should toggle
 - Filter badge count should update on filter sheet close
 - Back navigation from places list to home view should work as expected

Closes #7 
Closes #8

### CODE REVIEW

**Comment by lederer** [comment]
🥇 This is so awesome to see. Go @flibbertigibbet!

> Every place card currently shows the 'been' badge on the lower right, which serves as the button and anchor point for the popup menu of options. From the wireframes though, it appears that some variable set of applied badges for the place should appear on the bottom right. @lederer is that correct?

The default icon for that badge/button should be a plus sign (scroll down to "Silver Lake Park" on [this wireframe](https://marvelapp.com/4c295bb/screen/37236999) for an example). Those badges (not interested, want to go, been, liked) should be mutually exclusive, so if a place has one of those badges, its plus icon should be replaced with that badge.

> Also for clarification, should the 'liked' and 'want to go' buttons in the top bar serve as toggle-able filter shortcuts that behave just like the filter sheet options?

Yes exactly. And while the badges themselves are mutually exclusive, the filters are not. So someone could, say, enable _both_ "Liked" and "Want to go" (either in the top bar or via the filter sheet) and the list would include places matching either of those badges.

**Comment by flibbertigibbet** [comment]
screenshot_1520002716

**Comment by lederer** [comment]
I should add some additional clarification to filter behavior…

_Within_ a given filter, eg Category, multiple values are allowed and they should be OR'd. But _across_ filters should be AND'd.

Correct examples:
- (Nature OR Exercise)
- (Liked OR Want to go)
- (Nature) AND (Want to go)
- (Nature OR Exercise) AND (Liked OR Want to go)

**Comment by maurizi** [comment]
The badges in the upper-right corner of the Place card overlay on top of each other when a place has multiple badges.
screenshot from 2018-03-02 11-55-35

For some images it can be extremely difficult to discern the badge in the upper-right. @lederer what do you think of putting a colored circular background behind the badge, to increase the contrast?
screenshot from 2018-03-02 11-55-57

The number of active filters could use a _wee_ bit of left padding so it doesn't butt up against the left edge of the button.:
screenshot from 2018-03-02 11-56-51

**Comment by flibbertigibbet** [comment]
Have not seen the icon overlap (see screenshots above, where they are not overlapped). Could you please provide emulator information so I can try to reproduce?

Regarding icon backgrounds, we haven't had a styling pass yet; there will be some other icons that will need to be revisited as well.

**Comment by maurizi** [comment]
I tested on this:
screenshot from 2018-03-02 12-54-16

I'm totally fine with opening issues and letting these get taken care of in a later PR.

**Comment by flibbertigibbet** [comment]
Was able to reproduce the icon overlap on a Nexus emulator, fixed with a switch to constraint layout. Also changed up top bar button layout: the two filter shortcut buttons now have toggle-able state, and the other button's styling matches the other two better (which also fixes the badge padding.)

**Pull request merged**
