### PR TITLE
Feature/kak/place detail#16

### LINKED ISSUE #16: Destination detail view
Implement destination detail: [wireframe](https://marvelapp.com/4c295bb/screen/37237008).

Includes linking out to directions or [switching to map](https://marvelapp.com/4c295bb/screen/37237009) on button click, and displaying related event count.

### PR DESCRIPTION
**Pull request by flibbertigibbet**
## Overview

Adds the destination detail view, which opens when a destination is tapped from the list.

Display information about the destination. Implements some interactive elements as well.

## Demo

A Watershed Alliance location:
screenshot_1521664494

Popover for options:
screenshot_1521664450

Expanded description text:
screenshot_1521664445

Opened in external map:
screenshot_1521664505

## Notes

The count of related events currently always shows as two, as the events type has not yet been added to the database; that depends on #17.

The map button currently opens externally in Google Maps; opening within the app's own map view depends on #10.

When the descriptive text card is clicked, it expands, but the view does not scroll. We may want to open the full description in a separate view, as the descriptions themselves sometimes contain links, which could be made clickable if the whole view were not clickable to expand/collapse.

The image carousel only has one image in it currently, as support for uploading multiple images for a destination has not yet been implemented on the website. See: azavea/cac-tripplanner#1014

## Testing

 - Tap on a destination from the destination list
 - Detail view should open with correct destination information
 - The three buttons towards the bottom should open external browser/map as expected
 - Clicking second card ("Been here? Want to go?") should open popover

Closes #16

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
@lederer do you have thoughts on how the description text expand/collapse toggle should work? I'm thinking opening a separate view might make sense, but open to other suggestions.

**Comment by maurizi** [comment]
> @lederer do you have thoughts on how the description text expand/collapse toggle should work? I'm thinking opening a separate view might make sense, but open to other suggestions.

Rather than having the entire textview be clickable to expand/close, a dedicated see more/less button might work to allow clicking interior links.

**Comment by flibbertigibbet** [comment]
Updated to make description links clickable when card expanded, and to make the detail view scrollable.

**Comment by lederer** [comment]
> a dedicated see more/less button might work

Ideally this would appear within the block, centered on a new line. Sorta like this:

```
Nullam id dolor id nibh ultricies vehicula
ut id elit. Aenean lacinia bibendum nulla 
sed consectetur. Maecenas sed diam 
eget risus varius blandit sit amet non 
magna. Praesent commodo cursus …
           **SHOW MORE**
```

When expanded it would change to SHOW LESS.

**Comment by flibbertigibbet** [comment]
Went with making the whole block clickable, as well as any links within it. We can revisit that if we want to go with a specific expand/collapse text block instead.

**Pull request merged**
