### PR TITLE
Feature/kak/finish settings#109

### LINKED ISSUE #87: Add setting to opt in/out to crash reporting
Add an option under the settings menu where the user can opt in or out of crash reporting, and respect the setting. Currently, user will always be prompted before sending the log.

See [this documentation](https://docs.fabric.io/android/crashlytics/advanced-setup.html#using-the-privacy-dialog).

### LINKED ISSUE #109: Finish settings

### PR DESCRIPTION
**Pull request by flibbertigibbet**
## Overview: WIP

Implement settings screen, adding controls for posting data and turning notifications on and off.

Also adds 'About' activity.

## Demo

image

Closes #109 
Closes #87

### CODE REVIEW

**Comment by flibbertigibbet** [comment]
Added a first-launch opt-in dialog:

screenshot_1531336514

**Comment by flibbertigibbet** [comment]
@lederer @jcahail got ideas on text or other changes?

**Comment by jcahail** [comment]
This is looking great!

Here are some small suggestions (changes in **bold**): 

- "Notifications **Notify me** when **I'm** near a place I've **marked as someplace I liked or** want to go"
- "Enable **usage and crash** data sharing **Send** anonymous **reports about how I'm using the app and** when the app crashes"
- Reset anonymous app install ID **Have privacy concerns? Everything we track is anonymous, and you can reset this unique identifier at any time. None of the selections you've made will be lost.**
- "Terms of **S**ervice"
- "Privacy **Policy**"

On the second screen, I'd title it "Help us improve" and just reverse the order of "crash and usage data" to "usage and crash data"- otherwise, it reads just fine to me.

**Comment by lederer** [comment]
Nice. @jcahail What do you think of these tweaks:

- Notifications: "Notify me when I'm near a place I like or want to go."
- "Enable usage and crash data sharing" ->"Share usage and crash data"

**Comment by jcahail** [comment]
Sounds great!

**Comment by flibbertigibbet** [comment]
@lederer @jcahail we only notify on 'want to go' and not for 'like', so I'm dropping that part.

**Comment by flibbertigibbet** [comment]
@jcahail regarding capitalization of the headers for the terms of service and privacy policy: as a rule elsewhere only the first word is capitalized on headers and labels and such.

**Comment by flibbertigibbet** [comment]
How about this?

screenshot_1531750241


screenshot_1531750157

**Comment by lederer** [comment]
We should probably avoid "user flags" terminology in the UI. How about something like:

**Share anonymized location preferences**
Send us anonymous reports of which destinations and events you have marked as _been, liked, want to go,_ or _not interested_ so we can improve our listings.

@jcahail Feel free to polish that up.

@flibbertigibbet Just noticed some inconsistency with punctuation on this screen. Let's end all sentences with periods or question marks.

**Comment by flibbertigibbet** [comment]
I agree "user flags" is awkward and not obvious, but "location preferences" is not appropriate here, since we're not tracking user location.

**Comment by flibbertigibbet** [comment]
ID reset string was cut off above because an apostrophe needed escaping.

screenshot_1531752179

**Comment by lederer** [comment]
Yeah "location preferences" isn't great, though _preferences_ are not the same as _history_. 

Ultimately I'm trying to capture the meaning of "user-articulated history, opinion, and intent regarding destinations and events".

Another option might be "location interests". Or if we want to be more specific, "destination and event interests". 

Neither "interests" nor "preferences" quite captures the meaning of "been", but it may take too many words to achieve perfect precision here.

**Comment by jcahail** [comment]
Re: capitalization- that's fine. Both words will be capitalized in the titles within the documents themselves, but I agree that being consistent within the app is the way to go.

Re: "user flags"- what about "Share **selections** Let us know when you mark a place or event..."? Selections is vague enough to cover both interest and history, and implies that the user had to take an action.

**Comment by flibbertigibbet** [comment]
"Selections" works for me.

@lederer specifically I think we should avoid using the word "location" at all for the feature, since that implies geographic location of the user, which we do not record, and if we did, it would be PII. I want us to be very clear on what we record and don't, and we use but  *do not record* user location.

**Comment by lederer** [comment]
"Selections" is 💯

**Comment by flibbertigibbet** [comment]
image

**Comment by flibbertigibbet** [comment]
We seem to be good on text changes for now, so merging.

**Pull request merged**
